### ISSUE TITLE
CTL definition incomplete.

### ISSUE THREAD

**Issue by LD-devel** [HarryGoatleaf/model-checking#1]
https://github.com/HarryGoatleaf/model-checking/blob/afe60341dde0cd5089d0e587942e5542fc661748/notes/notes.qmd#L548

Should be 
` * $\Phi = \true \mid \Phi \lor \Phi \mid \neg \Phi$ `
since state formulas can consist of above relations on state formulas and path formulas must be quantified, I suppose.

**Comment by HarryGoatleaf** [comment]
oh ja, der teufel copy paste

**Comment by HarryGoatleaf** [comment]
fixed in b17597315308134589aed4d96f40d3953c1d3fbaO
